<a href="https://colab.research.google.com/github/Madhuanabala/breast-cancer/blob/unknown-mol-d%26fp/SubstructureCount_unknown.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
! wget https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
! unzip -o fingerprints_xml.zip

--2025-02-13 11:10:48--  https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip [following]
--2025-02-13 11:10:48--  https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10871 (11K) [application/zip]
Saving to: ‘fingerprints_xml.zip’

fingerprints_xml.zi 100%[===================>]  10.62K  --.-KB/s    in 0s

2025-02-13 11:10:49 (90.8 MB/s) - ‘fingerprints_xml.zip’ saved [10871/10871]

Archive:  fingerprints_xml.zip
  inflating: AtomPairs2DFingerprintCount.xml
  inflating: AtomPairs2DFingerprinter.xml
  inflating: EStateFingerprinter.xml
  inflating: ExtendedFingerprinter.xml
  inflating: Fingerprinter.xml
  inflating: GraphOnlyFingerprinter.xml
  inflating: KlekotaRothFingerprintCount.xml
  inflating: KlekotaRothFingerprinter.xml
  inflating: MACCSFingerprinter.xml
  inflating: PubchemFingerprinter.xml
  inflating: SubstructureFingerprintCount.xml
  inflating: SubstructureFingerprinter.xml

In [3]:
import glob
xml_files = glob.glob("*.xml")
xml_files.sort()
xml_files
FP_list = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'CDKextended',
 'CDK',
 'CDKgraphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

In [4]:
fp = dict(zip(FP_list, xml_files))
fp

{'AtomPairs2DCount': 'AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': 'AtomPairs2DFingerprinter.xml',
 'EState': 'EStateFingerprinter.xml',
 'CDKextended': 'ExtendedFingerprinter.xml',
 'CDK': 'Fingerprinter.xml',
 'CDKgraphonly': 'GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': 'KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': 'KlekotaRothFingerprinter.xml',
 'MACCS': 'MACCSFingerprinter.xml',
 'PubChem': 'PubchemFingerprinter.xml',
 'SubstructureCount': 'SubstructureFingerprintCount.xml',
 'Substructure': 'SubstructureFingerprinter.xml'}

In [5]:
df = pd.read_excel('/content/New Microsoft Excel Worksheet (2).xlsx')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Compound name  128 non-null    object
 1   smiles         128 non-null    object
 2   IMPPAT_id      128 non-null    object
dtypes: object(3)
memory usage: 3.1+ KB

In [6]:
df = pd.concat( [df['smiles']], axis=1 )
df.to_csv('molecule.smi', sep='\t', index=False, header=False)
df

                                                smiles
0        COc1c(OC)ccc2c1c[n+]1CCc3c(-c1c2)cc1c(c3)OCO1
1               Oc1cc(O)c2c(c1)oc(cc2=O)c1ccc(c(c1)O)O
2                              OC(=O)c1cc(O)c(c(c1)O)O
3    O=C(O[C@@H]1C[C@@](O)(C[C@H]([C@H]1O)O)C(=O)O)...
4    OC[C@]1(C)[C@H](O)CC[C@@]2([C@@H]1CCC(=C)[C@H]...
..                                                 ...
123         COC1=CC(=CC(=C1OC)OC)/C=C/C(=O)N2CCC=CC2=O
124       C1[C@H](OC2=C(C1=O)C=CC(=C2)O)C3=CC=C(C=C3)O
125  OCC1=C[C@H]2[C@H]3[C@@](C3(C)C)(O)[C@@H]([C@H]...
126  C[C@@H]1CC[C@]2([C@@H]([C@H]1C)C1=CC[C@H]3[C@@...
127            C=C[C@]1(C)CC[C@H](C[C@H]1C(=C)C)C(=C)C

[128 rows x 1 columns]

In [7]:
!pip install padelpy

Collecting padelpy
  Downloading padelpy-0.1.16-py3-none-any.whl.metadata (7.7 kB)
Downloading padelpy-0.1.16-py3-none-any.whl (20.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 74.0 MB/s eta 0:00:00
Installing collected packages: padelpy
Successfully installed padelpy-0.1.16

In [8]:
from padelpy import padeldescriptor

fingerprint = 'SubstructureCount'

fingerprint_output_file = ''.join([fingerprint,'.csv']) #CDK.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='molecule.smi',
                d_file=fingerprint_output_file, #'CDK.csv'
                #descriptortypes='SubstructureCountFingerprintCount.xml',
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=1,
                removesalt=True,
                log=True,
                fingerprints=True)

In [9]:
descriptors = pd.read_csv(fingerprint_output_file)
descriptors

,Name,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,SubFPC7,SubFPC8,SubFPC9,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,AUTOGEN_molecule_1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,7.0,7.0,2.0,0.0,0.0,0.0,0.0,16.0
1,AUTOGEN_molecule_2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5.0,5.0,1.0,0.0,0.0,0.0,0.0,14.0
2,AUTOGEN_molecule_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.0,4.0,1.0,0.0,0.0,0.0,0.0,7.0
3,AUTOGEN_molecule_4,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,15.0,15.0,5.0,1.0,0.0,0.0,0.0,14.0
4,AUTOGEN_molecule_5,2.0,5.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,22.0,22.0,3.0,1.0,0.0,0.0,0.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,AUTOGEN_molecule_124,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,9.0,9.0,6.0,2.0,0.0,0.0,0.0,13.0
124,AUTOGEN_molecule_125,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,6.0,6.0,1.0,0.0,0.0,0.0,0.0,14.0
125,AUTOGEN_molecule_126,4.0,1.0,4.0,1.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,23.0,23.0,1.0,1.0,0.0,0.0,0.0,14.0
126,AUTOGEN_molecule_127,8.0,9.0,5.0,5.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,32.0,32.0,0.0,0.0,0.0,0.0,0.0,13.0
127,AUTOGEN_molecule_128,3.0,3.0,2.0,1.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,12.0,12.0,3.0,0.0,0.0,0.0,0.0,6.0

In [10]:
# Load the original data to get 'imppat id'
original_df = pd.read_excel('/content/New Microsoft Excel Worksheet (2).xlsx')

# Load the generated descriptor file
descriptors_df = pd.read_csv(fingerprint_output_file)

# Concatenate 'imppat id' from the original data with descriptors
final_df = pd.concat([original_df[['IMPPAT_id']], descriptors_df], axis=1)

# Save the final output with 'imppat id'
final_output_file = f"{fingerprint}_with_imppat_id.csv"
final_df.to_csv(final_output_file, index=False)

print(f"Final file saved as {final_output_file}")

Final file saved as SubstructureCount_with_imppat_id.csv