<a href="https://colab.research.google.com/github/Madhuanabala/breast-cancer/blob/unknown-mol-d%26fp/unknown_cdk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [25]:
! wget https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
! unzip -o fingerprints_xml.zip

--2025-02-10 08:54:41--  https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip [following]
--2025-02-10 08:54:41--  https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10871 (11K) [application/zip]
Saving to: ‘fingerprints_xml.zip.1’

fingerprints_xml.zi 100%[===================>]  10.62K  --.-KB/s    in 0.001s

2025-02-10 08:54:42 (10.7 MB/s) - ‘fingerprints_xml.zip.1’ saved [10871/10871]

Archive:  fingerprints_xml.zip
  inflating: AtomPairs2DFingerprintCount.xml
  inflating: AtomPairs2DFingerprinter.xml
  inflating: EStateFingerprinter.xml
  inflating: ExtendedFingerprinter.xml
  inflating: Fingerprinter.xml
  inflating: GraphOnlyFingerprinter.xml
  inflating: KlekotaRothFingerprintCount.xml
  inflating: KlekotaRothFingerprinter.xml
  inflating: MACCSFingerprinter.xml
  inflating: PubchemFingerprinter.xml
  inflating: SubstructureFingerprintCount.xml
  inflating: SubstructureFingerprinter.xml

In [26]:
import glob
xml_files = glob.glob("*.xml")
xml_files.sort()
xml_files

['AtomPairs2DFingerprintCount.xml',
 'AtomPairs2DFingerprinter.xml',
 'EStateFingerprinter.xml',
 'ExtendedFingerprinter.xml',
 'Fingerprinter.xml',
 'GraphOnlyFingerprinter.xml',
 'KlekotaRothFingerprintCount.xml',
 'KlekotaRothFingerprinter.xml',
 'MACCSFingerprinter.xml',
 'PubchemFingerprinter.xml',
 'SubstructureFingerprintCount.xml',
 'SubstructureFingerprinter.xml']

In [27]:
FP_list = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'CDKextended',
 'CDK',
 'CDKgraphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

In [28]:
fp = dict(zip(FP_list, xml_files))
fp

{'AtomPairs2DCount': 'AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': 'AtomPairs2DFingerprinter.xml',
 'EState': 'EStateFingerprinter.xml',
 'CDKextended': 'ExtendedFingerprinter.xml',
 'CDK': 'Fingerprinter.xml',
 'CDKgraphonly': 'GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': 'KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': 'KlekotaRothFingerprinter.xml',
 'MACCS': 'MACCSFingerprinter.xml',
 'PubChem': 'PubchemFingerprinter.xml',
 'SubstructureCount': 'SubstructureFingerprintCount.xml',
 'Substructure': 'SubstructureFingerprinter.xml'}

In [29]:
df = pd.read_excel('/content/New Microsoft Excel Worksheet (2).xlsx')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Compound name  132 non-null    object
 1   smiles         132 non-null    object
 2   IMPPAT_id      132 non-null    object
dtypes: object(3)
memory usage: 3.2+ KB

In [36]:
df = pd.concat( [df['smiles']], axis=1 )
df.to_csv('molecule.smi', sep='\t', index=False, header=False)
df

                                                smiles
0        COc1c(OC)ccc2c1c[n+]1CCc3c(-c1c2)cc1c(c3)OCO1
1               Oc1cc(O)c2c(c1)oc(cc2=O)c1ccc(c(c1)O)O
2                              OC(=O)c1cc(O)c(c(c1)O)O
3    O=C(O[C@@H]1C[C@@](O)(C[C@H]([C@H]1O)O)C(=O)O)...
4    OC[C@]1(C)[C@H](O)CC[C@@]2([C@@H]1CCC(=C)[C@H]...
..                                                 ...
127         COC1=CC(=CC(=C1OC)OC)/C=C/C(=O)N2CCC=CC2=O
128       C1[C@H](OC2=C(C1=O)C=CC(=C2)O)C3=CC=C(C=C3)O
129  OCC1=C[C@H]2[C@H]3[C@@](C3(C)C)(O)[C@@H]([C@H]...
130  C[C@@H]1CC[C@]2([C@@H]([C@H]1C)C1=CC[C@H]3[C@@...
131            C=C[C@]1(C)CC[C@H](C[C@H]1C(=C)C)C(=C)C

[132 rows x 1 columns]

In [37]:
fp

{'AtomPairs2DCount': 'AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': 'AtomPairs2DFingerprinter.xml',
 'EState': 'EStateFingerprinter.xml',
 'CDKextended': 'ExtendedFingerprinter.xml',
 'CDK': 'Fingerprinter.xml',
 'CDKgraphonly': 'GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': 'KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': 'KlekotaRothFingerprinter.xml',
 'MACCS': 'MACCSFingerprinter.xml',
 'PubChem': 'PubchemFingerprinter.xml',
 'SubstructureCount': 'SubstructureFingerprintCount.xml',
 'Substructure': 'SubstructureFingerprinter.xml'}

In [38]:
!pip install padelpy

Requirement already satisfied: padelpy in /usr/local/lib/python3.11/dist-packages (0.1.16)

In [39]:
from padelpy import padeldescriptor

fingerprint = 'CDK'

fingerprint_output_file = ''.join([fingerprint,'.csv']) #CDK.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='molecule.smi',
                d_file=fingerprint_output_file, #'CDK.csv'
                #descriptortypes='CDKFingerprintCount.xml',
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

In [40]:
descriptors = pd.read_csv(fingerprint_output_file)
descriptors

,Name,FP1,FP2,FP3,FP4,FP5,FP6,FP7,FP8,FP9,...,FP1015,FP1016,FP1017,FP1018,FP1019,FP1020,FP1021,FP1022,FP1023,FP1024
0,AUTOGEN_molecule_1,0,0,1,0,1,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0
1,AUTOGEN_molecule_2,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
2,AUTOGEN_molecule_3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,AUTOGEN_molecule_4,0,0,0,0,0,1,0,0,0,...,1,1,1,0,0,0,0,1,0,0
4,AUTOGEN_molecule_5,0,0,0,1,0,1,1,0,0,...,1,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,AUTOGEN_molecule_128,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
128,AUTOGEN_molecule_129,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
129,AUTOGEN_molecule_130,0,0,0,1,0,1,1,0,0,...,1,0,0,0,0,0,0,0,0,0
130,AUTOGEN_molecule_131,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
131,AUTOGEN_molecule_132,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0